---
title: "gpg_signed_commits"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{gpg_signed_commits}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Signing Git commits Using PGP/GPG
[GNU Privacy Handbook](https://gnupg.org/gph/en/manual.html)

## GnuPG
[GnuPG: gpg](https://gnupg.org/index.html) version 2.x is installed along with [`Git for Windows`](https://gitforwindows.org/), so there is no need to install it separately. However, you must ensure that the GPG distribution provided with `Git` is high enough on the system path to be used by Git.  
```{}
# Which gpg executable is currently being used?
where gpg

# What version is being used?
gpg --version

# Where are keys being stored?
gpg --list-secret-keys --keyid-format=long
```


* Recent versions of `Git` have will have `gpg` version 2.x in the `C:\Program Files\Git\usr\bin` directory. 
* Add this folder to `Path` environment variable for your account. 
* After making this path change, reopen your IDE (PyCharm, RStudio), and run the above commands again to confirm gpg is using the specified gpg version. 

## Set git default editor
Change git's default editor from `vim` to `nano`. 
```{}
git config --global core.editor "nano"
```

## Generating a new GPG key
[Generating a new GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key)
* Open a shell/terminal window in your current working directory (root of git repo) and run the following commands: 

```{}
# Generate a GPG key using version 1 syntax
gpg --gen-key
```

```{}
# List the GPG keys on the current cumputer
gpg --list-secret-keys --keyid-format=long
```

```{}
# --list-secret-keys output:
D:\Workspace\rarr>gpg --list-secret-keys --keyid-format=long
/c/Users/B5PMMMPD/.gnupg/pubring.gpg
------------------------------------
sec   2048R/B68FE334FA0C2722 2022-03-04
uid                          Michael Dougherty <mike.p.doc.71@gmail.com>
ssb   2048R/91484B4037C3D166 2022-03-04
```

* In the example above, the `<key id>` that you will use in the next step is: `B68FE334FA0C2722`
* In the example above, this key can be referenced using its `uid`: `mike.p.doc.71@gmail.com` 

## Set Git to use this signing key
[Telling Git about your signing key](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key)

```{}
# Set user name and email
git config --global user.name "Your Name"
git config --global user.email you@example.com

# Set signing key on the current computer
git config --global user.signingkey <key id>

# Set git to sign all commits on the current computer
git config --global commit.gpgsign true
```

## Set the trust level of this key
The following commands will set the computer's GPG trust database. 
```{}
git config --global gpg.program "C:\Program Files\Git\usr\bin\gpg.exe"

# At the gpg prompt, enter the `trust` command to set the trust level
gpg> trust

# Follow the prompts to set "ultimate" trust level for this key.
# Save your changes
gpg> save
# Quit without saving changes
gpg> quit
```


## Test your new signing key
```{}
# in a git repo
touch test.txt
git add test.txt
git commit -m "test signed commits"
```

```{}
# View signatures of each commit
git log --show-signature
```


## Export public GPG key
[Export GPG key](https://docs.github.com/en/authentication/managing-commit-signature-verification/generating-a-new-gpg-key)

```{}
# List the GPG keys on the current computer
gpg --list-secret-keys --keyid-format=long

# Prints the GPG public key ID, in ASCII armor format
gpg --armor --export <key>
```

* Copy your GPG public key, beginning with `-----BEGIN PGP PUBLIC KEY BLOCK-----` and ending with `-----END PGP PUBLIC KEY BLOCK-----`. 
* Use this copied text in the next step.


## Adding a new GPG public key to your GitHub account
[Adding a new GPG key to your GitHub account](https://docs.github.com/en/authentication/managing-commit-signature-verification/adding-a-new-gpg-key-to-your-github-account)

* Add this GPG public key to GitHub. 

## Check your signed commit
[Check your signed commit](https://www.garrickadenbuie.com/blog/signed-verified-git-commits-keybase-rstudio/)

```{}
# in a git repo
touch test.txt
git add test.txt
git commit -m "test signed commits"
```


## Export your GPG private key for use on another computer
[Import your GPG key on another computer](https://www.garrickadenbuie.com/blog/signed-verified-git-commits-keybase-rstudio/#import-your-gpg-key-on-another-computer)

```{}
# From the first computer where you generated the GPG key, export the 
# ASCII armored private key
gpg -a --export-secret-keys <key> 
```

* Copy your GPG private key, beginning with `-----BEGIN PGP PRIVATE KEY BLOCK-----` and ending with `-----END PGP PRIVATE KEY BLOCK-----`. 
* Add the exported text of the GPG private key to your secure password database.
* This will allow you to install this GPG private key on any other computers you use. 


## Import your GPG private key on a computer
* On another computer, open your secure password database. 
* Copy the private key text to a temp file in your shell's current working directory. 

```{}
# Import the GPG private key
gpg --import <tempfile>

# List the GPG keys on the current computer
gpg --list-secret-keys --keyid-format=long 
```

* If the key import is successful, delete the temp file to ensure the security of your private key. 


## Set Git to use this signing key
[Telling Git about your signing key](https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key)

```{}
# Set user name and email
git config --global user.name "Your Name"
git config --global user.email you@example.com

# Set signing key
git config --global user.signingkey <key>

# Set git to sign all commits
git config --global commit.gpgsign true
```

## Set the trust level of this key
The following commands will set the computer's GPG trust database. 
```{}
gpg --edit-key mike.p.doc.71@gmail.com

# At the gpg prompt, enter the `trust` command to set the trust level
gpg> trust
gpg> save
```


